# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: outdent, indent
Layout/AccessModifierIndentation:
  Exclude:
    - 'app/controllers/brands_controller.rb'
    - 'bin/bundle'

# Offense count: 56
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: with_first_argument, with_fixed_indentation


# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleAlignWith.
# SupportedStylesAlignWith: either, start_of_block, start_of_line
Layout/BlockAlignment:
  include:
    # - 'config/routes.rb'
    # - 'spec/system/brands_spec.rb'

# Offense count: 14
# Cop supports --auto-correct.
Layout/ClosingParenthesisIndentation:
  Exclude:
    - 'db/seeds.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/system/brands_spec.rb'
    - 'spec/system/products_spec.rb'
    - 'spec/system/reviews_spec.rb'

# Offense count: 3
# Cop supports --auto-correct.
Layout/CommentIndentation:
  Exclude:
    - 'app/controllers/brands_controller.rb'
    - 'app/models/product.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleAlignWith, Severity.
# SupportedStylesAlignWith: start_of_line, def
Layout/DefEndAlignment:
  Exclude:
    - 'app/controllers/brands_controller.rb'
    - 'app/models/brand.rb'

# Offense count: 1
# Cop supports --auto-correct.
Layout/ElseAlignment:
  Exclude:
    - 'app/controllers/brands_controller.rb'

# Offense count: 6
# Cop supports --auto-correct.
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/bundle'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EmptyLineBetweenMethodDefs, EmptyLineBetweenClassDefs, EmptyLineBetweenModuleDefs, AllowAdjacentOneLineDefs, NumberOfEmptyLines.
Layout/EmptyLineBetweenDefs:
  Exclude:
    - 'app/controllers/pages_controller.rb'
    - 'app/helpers/sessions_helper.rb'

# Offense count: 3
# Cop supports --auto-correct.
Layout/EmptyLines:
  Exclude:
    - 'Gemfile'
    - 'config/environments/development.rb'
    - 'db/migrate/20210530074837_devise_create_users.rb'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: around, only_before
Layout/EmptyLinesAroundAccessModifier:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/brands_controller.rb'
    - 'app/controllers/likes_controller.rb'
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/reviews_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines, beginning_only, ending_only
Layout/EmptyLinesAroundClassBody:
  Exclude:
    - 'app/controllers/brands_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleAlignWith, Severity.
# SupportedStylesAlignWith: keyword, variable, start_of_line
Layout/EndAlignment:
  Exclude:
    - 'app/controllers/brands_controller.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: consistent, consistent_relative_to_receiver, special_for_inner_method_call, special_for_inner_method_call_in_parentheses
Layout/FirstArgumentIndentation:
  Exclude:
    - 'spec/system/products_spec.rb'
    - 'spec/system/reviews_spec.rb'

# Offense count: 22
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleStyles, EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle.
# SupportedHashRocketStyles: key, separator, table
# SupportedColonStyles: key, separator, table
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Layout/HashAlignment:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/brands_helper.rb'
    - 'app/models/brand.rb'
    - 'app/models/product.rb'
    - 'app/models/review.rb'
    - 'app/models/user.rb'
    - 'db/seeds.rb'
    - 'spec/models/review_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/system/pages_index_spec.rb'
    - 'spec/system/users_spec.rb'

# Offense count: 35
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: normal, indented_internal_methods
Layout/IndentationConsistency:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/brands_controller.rb'
    - 'app/controllers/likes_controller.rb'
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/reviews_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/models/brand.rb'
    - 'config/routes.rb'
    - 'spec/system/brands_spec.rb'
    - 'spec/system/products_spec.rb'
    - 'spec/system/reviews_spec.rb'

# Offense count: 110
# Cop supports --auto-correct.
# Configuration parameters: IndentationWidth, EnforcedStyle.
# SupportedStyles: spaces, tabs
Layout/IndentationStyle:
  Exclude:
    - 'app/controllers/brands_controller.rb'
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/reviews_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/helpers/sessions_helper.rb'
    - 'app/models/brand.rb'
    - 'app/models/product.rb'
    - 'config/routes.rb'

# Offense count: 51
# Cop supports --auto-correct.
# Configuration parameters: Width, IgnoredPatterns.
Layout/IndentationWidth:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/brands_controller.rb'
    - 'app/controllers/likes_controller.rb'
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/reviews_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/helpers/sessions_helper.rb'
    - 'app/models/brand.rb'
    - 'spec/system/brands_spec.rb'
    - 'spec/system/pages_index_spec.rb'

# Offense count: 23
# Cop supports --auto-correct.
# Configuration parameters: AllowDoxygenCommentStyle, AllowGemfileRubyComment.
Layout/LeadingCommentSpace:
  Exclude:
    - 'spec/models/brand_spec.rb'
    - 'spec/models/product_spec.rb'
    - 'spec/models/review_spec.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: symmetrical, new_line, same_line
Layout/MultilineMethodCallBraceLayout:
  Exclude:
    - 'spec/system/brands_spec.rb'

# Offense count: 5
# Cop supports --auto-correct.
Layout/SpaceAfterColon:
  Exclude:
    - 'app/controllers/reviews_controller.rb'
    - 'spec/models/like_spec.rb'

# Offense count: 7
# Cop supports --auto-correct.
Layout/SpaceAfterComma:
  Exclude:
    - 'app/controllers/reviews/picks_controller.rb'
    - 'app/models/user.rb'
    - 'spec/system/likes_spec.rb'
    - 'spec/system/reviews_spec.rb'

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, EnforcedStyleForExponentOperator.
# SupportedStylesForExponentOperator: space, no_space
Layout/SpaceAroundOperators:
  Exclude:
    - 'db/seeds.rb'
    - 'spec/system/reviews_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Layout/SpaceBeforeComma:
  Exclude:
    - 'spec/models/user_spec.rb'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBrackets.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBrackets: space, no_space
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'
    - 'db/migrate/20210531072122_create_active_storage_tables.active_storage.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForEmptyBraces.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBraces: space, no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: space, no_space
Layout/SpaceInsideParens:
  Exclude:
    - 'spec/models/brand_spec.rb'
    - 'spec/models/review_spec.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: final_newline, final_blank_line
Layout/TrailingEmptyLines:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/likes_controller.rb'
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/reviews_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/models/brand.rb'
    - 'app/views/reviews/picks.json.jbuilder'
    - 'config/initializers/pagy.rb'
    - 'db/seeds.rb'
    - 'spec/support/capybara.rb'
    - 'spec/support/factory_bot.rb'
    - 'spec/system/likes_spec.rb'
    - 'spec/system/users_spec.rb'

# Offense count: 234
# Cop supports --auto-correct.
# Configuration parameters: AllowInHeredoc.
Layout/TrailingWhitespace:
  Enabled: false

# Offense count: 1
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'spec/rails_helper.rb'

# Offense count: 2
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 21

# Offense count: 40
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
# IgnoredMethods: refine
Metrics/BlockLength:
  Max: 458

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 10

# Offense count: 5
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 18

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 10

# Offense count: 60
# Configuration parameters: AllowedChars.
Style/AsciiComments:
  Exclude:
    - 'app/helpers/sessions_helper.rb'
    - 'spec/models/brand_spec.rb'
    - 'spec/models/product_spec.rb'
    - 'spec/models/review_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/requests/pages_request_spec.rb'
    - 'spec/system/pages_index_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/reviews/picks_controller.rb'
    - 'app/controllers/users/confirmations_controller.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/controllers/users/passwords_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/controllers/users/unlocks_controller.rb'

# Offense count: 24
Style/Documentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: compact, expanded
Style/EmptyMethod:
  Exclude:
    - 'app/controllers/pages_controller.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'

# Offense count: 83
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/brands_controller.rb'

# Offense count: 2
Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/controllers/likes_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowIfModifier.
Style/IfInsideElse:
  Exclude:
    - 'app/controllers/brands_controller.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/brands_controller.rb'
    - 'bin/bundle'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 6

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'app/controllers/application_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: SafeForConstants.
Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantInterpolation:
  Exclude:
    - 'spec/system/reviews_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'app/models/brand.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: .
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Offense count: 2
# Cop supports --auto-correct.
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

# Offense count: 1
# Cop supports --auto-correct.
Style/StringConcatenation:
  Exclude:
    - 'app/helpers/application_helper.rb'

# Offense count: 796
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/brands_controller.rb'
    - 'app/controllers/likes_controller.rb'
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/reviews_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'config/routes.rb'
    - 'db/migrate/20210531072122_create_active_storage_tables.active_storage.rb'
    - 'db/migrate/20210604070035_create_likes.rb'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInArguments:
  Exclude:
    - 'db/seeds.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/system/brands_spec.rb'
    - 'spec/system/products_spec.rb'
    - 'spec/system/reviews_spec.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 5

# Offense count: 19
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 190
