inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile
    - Gemfile.lock
    - 'tmp/**/*'
    - 'node_modules/**/*'