inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - 'tmp/**/*'
    - 'node_modules/**/*'
Layout/BlockAlignment:
  include:
    - 'config/routes.rb'