version: '3'
services: 
  web:
    build: .
    command: rails s -b '0.0.0.0'
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
      SELENIUM_REMOTE_URL: http://webdriver_chrome:5090/wd/hub
    volumes:
      - .:/smar-003:cached
      - node_modules:/smar-003/node_modules:cached
      - yarn_cache:/usr/local/share/.cache/yarn/v6:cached
      - bundle:/bundle:cached
    tmpfs:
      - /tmp
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
      - "4000:4000"
    links:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/smar-003:cached
      - bundle:/bundle:cached
      - node_modules:/smar-003/node_modules:cached
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    tty: false
    stdin_open: false
    ports:
      - "3035:3035"
    links:
      - db
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5900:5900"
volumes:
  bundle:
  node_modules:
  mysql-data:
    driver: local
  yarn_cache: