default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: mysql2
  encoding: utf8mb4
  ## For ENV CentOS7 & AWS
  socket: /var/lib/mysql/mysql.sock
  ## For AWS
  username: <%= ENV['AWS_RDS_USERNAME'] %>
  password: <%= ENV['AWS_RDS_PASSWORD'] %>
  host:  <%= ENV['AWS_RDS_END_POINT'] %>
  ## For MacOS
  # username: root
  # password: '@asFay4563'
  # socket: /tmp/mysql.sock
development:
  <<: *default
  database: smar_003_development
test:
  <<: *default
  database: smar_003_test
production:
  <<: *default
  database: smar_003_production